name: FlyTrack Backend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: aerosmart
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Dar permisos a Gradle
        run: chmod +x gradlew

      - name: Compilar proyecto
        run: ./gradlew build -x test

      - name: Ejecutar pruebas unitarias
        run: ./gradlew test
        env:
          DB_URL: jdbc:postgresql://localhost:5432/aerosmart
          DB_USER: postgres
          DB_PASSWORD: postgres
          JWT_SECRET: FlyTrackSuperSecretKeyParaJWT2025AeroPuertoSmart!
          JWT_EXPIRATION: 86400000

      

      - name: Login a Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: flytrackregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build y push imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: flytrackregistry.azurecr.io/flytrack-backend:latest

      - name: Desplegar en Azure Web App
        if: github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
          app-name: flytrack-backend-app
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: flytrackregistry.azurecr.io/flytrack-backend:latest